package auth

import "errors"

var (
	ErrInvalidCredentials    = errors.New("invalid credentials")
	ErrInvalidInput          = errors.New("invalid input")
	ErrEmailAlreadyExists    = errors.New("email already exists")
	ErrEmailDeliveryFailed   = errors.New("email delivery failed")
	ErrEmailNotVerified      = errors.New("email is not verified")
	ErrUserBlocked           = errors.New("user is blocked")
	ErrInvalidToken          = errors.New("invalid token")
	ErrTokenExpired          = errors.New("token expired")
	ErrMFACodeRequired       = errors.New("2fa code required")
	ErrInvalidMFACode        = errors.New("invalid 2fa code")
	ErrMFATicketExpired      = errors.New("mfa ticket expired")
	ErrTooManyRequests       = errors.New("too many requests")
	ErrCSRFViolation         = errors.New("csrf validation failed")
	ErrWeakPassword          = errors.New("password does not meet policy")
	ErrUnauthorized          = errors.New("unauthorized")
	ErrForbidden             = errors.New("forbidden")
	ErrSessionNotFound       = errors.New("session not found")
	ErrSessionCompromised    = errors.New("session compromised")
	ErrActionTokenNotFound   = errors.New("action token not found")
	ErrPasswordChangeDenied  = errors.New("password change denied")
	ErrTwoFactorAlreadyOn    = errors.New("2fa already enabled")
	ErrTwoFactorNotSetup     = errors.New("2fa secret is not configured")
	ErrTwoFactorNotEnabled   = errors.New("2fa is not enabled")
	ErrInvalidRefreshToken   = errors.New("invalid refresh token")
	ErrSuspiciousLogin       = errors.New("suspicious login detected")
	ErrRegistrationBlocked   = errors.New("registration blocked")
	ErrUserNotFound          = errors.New("user not found")
	ErrSavedTraitSetNotFound = errors.New("saved trait set not found")
	ErrTraitTargetNotFound   = errors.New("trait target not found")
)
